name: appweb # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: appweb with Python and Flask # 79 char long summary
description: This is appweb. it's a website developed with Python and Flask.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [arm64, armhf, amd64]
  
apps:
  appweb:
    command: bin/appweb
    plugs: [home, network, network-bind]
    
parts:
  appweb:
    # See 'snapcraft plugins'
    plugin: python
    python-version: python3
    source: .
